// Generates src/ui/icons/generated.ts from Material Symbols Rounded (weight 400).
// Add names to ICONS and run `npm run icons`. Each icon exports [outlinedPath, filledPath].
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ICONS = [
  "account_circle", "add", "archive", "arrow_back", "arrow_drop_down", "arrow_forward",
  "assignment_return", "auto_stories", "badge", "barcode_scanner", "block", "book_2", "bookmark",
  "calendar_month", "cancel", "category", "celebration", "check", "check_circle", "chevron_left",
  "chevron_right", "close", "content_copy", "content_paste", "contrast", "dark_mode", "delete",
  "done_all", "download", "edit", "error", "event", "favorite", "filter_list",
  "flashlight_off", "flashlight_on", "group_add", "groups", "healing", "help", "history", "home", "keyboard_arrow_down", "keyboard_arrow_up", "library_add_check", "book_4", "book_ribbon", "move_to_inbox", "outbox",
  "hourglass_empty", "image", "info", "input", "inventory_2", "keyboard", "label", "library_add",
  "library_books", "light_mode", "link", "local_library", "lock", "logout", "mail", "menu",
  "menu_book", "menu_open", "more_horiz", "more_vert", "move_item", "numbers", "open_in_new",
  "output", "palette", "person", "person_add", "person_remove", "photo_camera", "print",
  "qr_code_scanner", "refresh", "remove", "report", "restart_alt", "schedule", "school", "search",
  "settings", "shelves", "sort", "star", "swap_vert", "sync", "tune", "undo", "unarchive",
  "upload_file", "visibility", "visibility_off", "warning", "waving_hand", "grid_view", "view_list", "admin_panel_settings",
];

const root = path.resolve(import.meta.dirname, "..");
const dir = path.join(root, "node_modules", "@material-symbols", "svg-400", "rounded");

function readPath(file) {
  const full = path.join(dir, file);
  if (!existsSync(full)) throw new Error(`Material Symbol not found: ${file}`);
  const svg = readFileSync(full, "utf8");
  const match = svg.match(/<path d="([^"]+)"/);
  if (!match) throw new Error(`No path in ${file}`);
  return match[1];
}

const toExportName = (name) =>
  "icon" + name.split("_").map((part) => part[0].toUpperCase() + part.slice(1)).join("");

const lines = [
  "// Generated by scripts/build-icons.mjs from @material-symbols/svg-400 (rounded). Do not edit.",
  "// Each entry is [outlined path, filled path] in a 0 -960 960 960 viewBox.",
  "export type IconData = readonly [outlined: string, filled: string];",
  "",
];
for (const name of [...new Set(ICONS)].sort()) {
  const outlined = readPath(`${name}.svg`);
  const filled = existsSync(path.join(dir, `${name}-fill.svg`)) ? readPath(`${name}-fill.svg`) : outlined;
  lines.push(`export const ${toExportName(name)}: IconData = [${JSON.stringify(outlined)}, ${JSON.stringify(filled)}];`);
}

writeFileSync(path.join(root, "src", "ui", "icons", "generated.ts"), lines.join("\n") + "\n");
console.info(`Generated ${ICONS.length} icons.`);
